// Code generated by mockery v2.18.0. DO NOT EDIT.

package mocks

import (
	models "PlayerWon/models"

	mock "github.com/stretchr/testify/mock"
)

// IAdsController is an autogenerated mock type for the IAdsController type
type IAdsController struct {
	mock.Mock
}

// ObtainNewAd provides a mock function with given fields: requestData
func (_m *IAdsController) ObtainNewAd(requestData models.RequestAd) (models.AdResponse, error) {
	ret := _m.Called(requestData)

	var r0 models.AdResponse
	if rf, ok := ret.Get(0).(func(models.RequestAd) models.AdResponse); ok {
		r0 = rf(requestData)
	} else {
		r0 = ret.Get(0).(models.AdResponse)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(models.RequestAd) error); ok {
		r1 = rf(requestData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIAdsController interface {
	mock.TestingT
	Cleanup(func())
}

// NewIAdsController creates a new instance of IAdsController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIAdsController(t mockConstructorTestingTNewIAdsController) *IAdsController {
	mock := &IAdsController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
