// Code generated by mockery v2.18.0. DO NOT EDIT.

package mocks

import (
	models "PlayerWon/models"

	mock "github.com/stretchr/testify/mock"
)

// IAdsService is an autogenerated mock type for the IAdsService type
type IAdsService struct {
	mock.Mock
}

// RequestAdFromServer provides a mock function with given fields:
func (_m *IAdsService) RequestAdFromServer() ([]models.Ad, error) {
	ret := _m.Called()

	var r0 []models.Ad
	if rf, ok := ret.Get(0).(func() []models.Ad); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Ad)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewIAdsService interface {
	mock.TestingT
	Cleanup(func())
}

// NewIAdsService creates a new instance of IAdsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIAdsService(t mockConstructorTestingTNewIAdsService) *IAdsService {
	mock := &IAdsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
