// Code generated by mockery v2.18.0. DO NOT EDIT.

package mocks

import (
	models "PlayerWon/models"

	mock "github.com/stretchr/testify/mock"
)

// IAdsDal is an autogenerated mock type for the IAdsDal type
type IAdsDal struct {
	mock.Mock
}

// GetAdsViewedTodayByUser provides a mock function with given fields: userID
func (_m *IAdsDal) GetAdsViewedTodayByUser(userID string) ([]string, error) {
	ret := _m.Called(userID)

	var r0 []string
	if rf, ok := ret.Get(0).(func(string) []string); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterNewAdForUser provides a mock function with given fields: userAdData
func (_m *IAdsDal) RegisterNewAdForUser(userAdData models.UserViewedAd) {
	_m.Called(userAdData)
}

type mockConstructorTestingTNewIAdsDal interface {
	mock.TestingT
	Cleanup(func())
}

// NewIAdsDal creates a new instance of IAdsDal. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIAdsDal(t mockConstructorTestingTNewIAdsDal) *IAdsDal {
	mock := &IAdsDal{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
